# Generated by Django 4.1.5 on 2023-02-11 04:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_address_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='uuid',
        ),
        migrations.AddField(
            model_name='customer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
