# Generated by Django 4.1.5 on 2023-02-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_address_uuid_customer_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='uuid',
            field=models.UUIDField(default=None, editable=False, unique=True),
        ),
    ]
