# Generated by Django 4.1.5 on 2023-03-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_customer_username_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_date',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_date_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
