# Generated by Django 4.1.5 on 2023-03-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_orders_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
