# Generated by Django 4.1.5 on 2023-03-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orders_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_date_time',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_time',
            field=models.TimeField(default=None),
        ),
    ]
